name: Release

on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: ${{ GITHUB_REF##*/ }}
      run: |
        echo ${BRANCH_NAME}
        echo $BRANCH_NAME
        gh release create ${BRANCH_NAME} \
            --repo="$GITHUB_REPOSITORY" \
            --title="${BRANCH_NAME}" \
            --generate-notes