name: Release

on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write

env:
  TAG: ${{ github.ref_name }}

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create tag
      run: | 
        echo OUTPUT="$(git ls-remote --tags origin | grep ${TAG##*/})" >> $GITHUB_ENV

        if [[ -n "$OUTPUT" ]]; then
          git tag "${TAG##*/}-rc-`expr "${OUTPUT:0-1}" + 1`"
        else
          git tag "${TAG##*/}-rc-1"
        fi
        git push origin --tags
      shell: bash

    # - name: Create release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     echo ${TAG##*/}
    #     gh release create ${TAG##*/} \
    #         --repo="$GITHUB_REPOSITORY" \
    #         --title="${TAG##*/}rc" \
    #         --generate-notes
