name: Release

on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write

env:
  TAG: ${{ github.ref_name }}

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create tag
      run: |
        echo VERSION="${TAG##*/}" >> $GITHUB_ENV
        echo RC="$(git ls-remote --tags origin | grep $VERSION" >> $GITHUB_ENV
        echo "${RC:0-1}"

        if [[ -n "$RC" ]]; then
          echo "${TAG}-rc-`expr "${RC:0-1}" + 1`"
        else
          echo "${TAG}-rc-1"
        fi
      shell: bash

    # - name: Create release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     echo ${TAG##*/}
    #     gh release create ${TAG##*/} \
    #         --repo="$GITHUB_REPOSITORY" \
    #         --title="${TAG##*/}rc" \
    #         --generate-notes
