name: Release

on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write

env:
  TAG: ${{ github.ref_name }}

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create tag
      run: |
        echo CURRENT_VERSION="${TAG##*/}"
        echo $CURRENT_VERSION

        echo OUTPUT="$(git ls-remote --tags origin | grep $CURRENT_VERSION" >> $GITHUB_ENV
        echo "${OUTPUT:0-1}"

        if [[ -n "$OUTPUT" ]]; then
          echo "${CURRENT_VERSION}-rc-`expr "${OUTPUT:0-1}" + 1`"
        else
          echo "${CURRENT_VERSION}-rc-1"
        fi
      shell: bash

    # - name: Create release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: |
    #     echo ${TAG##*/}
    #     gh release create ${TAG##*/} \
    #         --repo="$GITHUB_REPOSITORY" \
    #         --title="${TAG##*/}rc" \
    #         --generate-notes
