name: Release

on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      env:
        PYPI_VERSION: ${GITHUB_REF##*/}
      shell: bash

    - name: Pypi
      shell: bash
      run: echo ${PYPI_VERSION}
