name: Release

on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${GITHUB_REF##*/}
      run: |
        echo ${GITHUB_REF##*/}
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${tag#v}" \
            --generate-notes